// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/gen-docs.mjs

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "tutorialSidebar": [
    {
      "type": "category",
      "label": "contact",
      "collapsed": true,
      "items": [
        {
          "type": "doc",
          "id": "contact/emails"
        },
        {
          "type": "doc",
          "id": "contact/links"
        },
        {
          "type": "doc",
          "id": "contact/faq"
        }
      ]
    },
    {
      "type": "category",
      "label": "scripts",
      "collapsed": true,
      "items": [
        {
          "type": "category",
          "label": "appearance",
          "collapsed": true,
          "items": [
            {
              "type": "category",
              "label": "apconfig",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/overview"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/system"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/ui"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/pricing"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/commands"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/clothes-off"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/peds"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/stores"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/clothing-rooms"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/outfits"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/tattoos"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apconfig/opposites"
                }
              ]
            },
            {
              "type": "category",
              "label": "apdev",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "scripts/appearance/apdev/overrides"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apdev/events"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apdev/exports"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apdev/data-format"
                }
              ]
            },
            {
              "type": "category",
              "label": "apintegrations",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "scripts/appearance/apintegrations/overview"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apintegrations/compatibility"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apintegrations/qbcore"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apintegrations/illenium-format"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apintegrations/walkstyle"
                }
              ]
            },
            {
              "type": "category",
              "label": "apusage",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "scripts/appearance/apusage/overview"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apusage/clothing-menu"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apusage/barber-surgeon"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apusage/tattoo-menu"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apusage/outfit-system"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apusage/uniform-system"
                },
                {
                  "type": "doc",
                  "id": "scripts/appearance/apusage/face-cache"
                }
              ]
            },
            {
              "type": "doc",
              "id": "scripts/appearance/overview"
            },
            {
              "type": "doc",
              "id": "scripts/appearance/installation"
            },
            {
              "type": "doc",
              "id": "scripts/appearance/database"
            },
            {
              "type": "doc",
              "id": "scripts/appearance/troubleshooting"
            }
          ]
        },
        {
          "type": "category",
          "label": "freecam",
          "collapsed": true,
          "items": [
            {
              "type": "category",
              "label": "fcconfig",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcconfig/system"
                },
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcconfig/ui"
                },
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcconfig/visual"
                },
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcconfig/environment"
                },
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcconfig/effects"
                },
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcconfig/settings"
                }
              ]
            },
            {
              "type": "category",
              "label": "fcusage",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcusage/photo"
                },
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcusage/overrides"
                },
                {
                  "type": "doc",
                  "id": "scripts/freecam/fcusage/migration"
                }
              ]
            },
            {
              "type": "doc",
              "id": "scripts/freecam/overview"
            },
            {
              "type": "doc",
              "id": "scripts/freecam/installation"
            }
          ]
        },
        {
          "type": "category",
          "label": "posdevice",
          "collapsed": true,
          "items": [
            {
              "type": "category",
              "label": "pdconfig",
              "collapsed": true,
              "items": [
                {
                  "type": "category",
                  "label": "pdui",
                  "collapsed": true,
                  "items": [
                    {
                      "type": "doc",
                      "id": "scripts/posdevice/pdconfig/pdui/overview"
                    },
                    {
                      "type": "doc",
                      "id": "scripts/posdevice/pdconfig/pdui/credit-card-ui"
                    }
                  ]
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdconfig/overview"
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdconfig/system-settings"
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdconfig/debug-settings"
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdconfig/history-system"
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdconfig/override-settings"
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdconfig/event-triggers"
                }
              ]
            },
            {
              "type": "category",
              "label": "pdusage",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdusage/overview"
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdusage/qb-target"
                },
                {
                  "type": "doc",
                  "id": "scripts/posdevice/pdusage/events-and-exports"
                }
              ]
            },
            {
              "type": "doc",
              "id": "scripts/posdevice/installation"
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "vehicles",
      "collapsed": true,
      "items": [
        {
          "type": "category",
          "label": "maroonshupack",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "vehicles/maroonshupack/overview"
            }
          ]
        },
        {
          "type": "category",
          "label": "maroonshupackwoems",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "vehicles/maroonshupackwoems/overview"
            }
          ]
        },
        {
          "type": "doc",
          "id": "vehicles/overview"
        }
      ]
    },
    {
      "type": "doc",
      "id": "index"
    }
  ]
};

module.exports = sidebars;
