// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/gen-docs.mjs

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "tutorialSidebar": [
    {
      "type": "category",
      "label": "SCRIPTS",
      "collapsed": true,
      "items": [
        {
          "type": "category",
          "label": "POS DEVICE",
          "collapsed": true,
          "items": [
            {
              "type": "category",
              "label": "CONFIGURATION",
              "collapsed": true,
              "items": [
                {
                  "type": "category",
                  "label": "UI",
                  "collapsed": true,
                  "items": [
                    {
                      "type": "doc",
                      "id": "SCRIPTS/POS DEVICE/CONFIGURATION/UI/overview"
                    },
                    {
                      "type": "doc",
                      "id": "SCRIPTS/POS DEVICE/CONFIGURATION/UI/general-ui"
                    },
                    {
                      "type": "doc",
                      "id": "SCRIPTS/POS DEVICE/CONFIGURATION/UI/layout"
                    },
                    {
                      "type": "doc",
                      "id": "SCRIPTS/POS DEVICE/CONFIGURATION/UI/credit-card-ui"
                    }
                  ]
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/CONFIGURATION/overview"
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/CONFIGURATION/system-settings"
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/CONFIGURATION/debug-settings"
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/CONFIGURATION/history-system"
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/CONFIGURATION/override-settings"
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/CONFIGURATION/event-triggers"
                }
              ]
            },
            {
              "type": "category",
              "label": "USAGE",
              "collapsed": true,
              "items": [
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/USAGE/overview"
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/USAGE/qb-target"
                },
                {
                  "type": "doc",
                  "id": "SCRIPTS/POS DEVICE/USAGE/events-and-exports"
                }
              ]
            },
            {
              "type": "doc",
              "id": "SCRIPTS/POS DEVICE/installation"
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "VEHICLES",
      "collapsed": true,
      "items": [
        {
          "type": "doc",
          "id": "VEHICLES/overview"
        }
      ]
    },
    {
      "type": "doc",
      "id": "index"
    }
  ]
};

module.exports = sidebars;
